### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas'

### ISSUE THREAD

**Issue by My12123** [dmMaze/comic-text-detector#7]
![2023-02-02_18-22-19](https://user-images.githubusercontent.com/49092250/216366334-816bd021-3fe5-44b6-bd95-987f787d7b16.png)

**Comment by bropines** [comment]
`pip install pandas`

**Comment by dmMaze** [comment]
pip install -r requirements.txt
Please learn some basic python first.
And I'll block you if you keep opening issue like this.
